name: highlights_plugin
description: Dart implementation of highlights syntax highlighting engine.
version: 0.1.0
repository: https://github.com/SnipMeDev/highlights_plugin
homepage: https://github.com/SnipMeDev/highlights_plugin

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: 2.1.8
  json_annotation: 4.9.0

  collection: 1.18.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  build_runner: 2.4.13
  json_serializable: 6.8.0

flutter:
  plugin:
    platforms:
      android:
        package: dev.snipme.highlights_plugin
        pluginClass: HighlightsPlugin
      ios:
        pluginClass: HighlightsPlugin
#      linux:
#        pluginClass: HighlightsPlugin
#      macos:
#        pluginClass: HighlightsPlugin
#      windows:
#        pluginClass: HighlightsPluginCApi
#      web:
#        pluginClass: HighlightsPluginWeb
#        fileName: highlights_plugin_web.dart